Create a new documentation for crossplots in spanish
geopozo/pozo-py pull request #13
Opened 2024-03-20 13:51 UTC by neyberson

Create a .md file with the description about crossplots in spanish

2024-03-21 17:22 UTC, ayjayt requested changes

2024-03-21 17:22 UTC, ayjayt commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# colors: lista de objetos de pozo para crear una gama de colores. Puede incluir "depth" o ser None para no tener colores.
dos lineas porfa, con indentación

2024-03-21 17:22 UTC, ayjayt commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# establece un color_range, auto, o False.
creo que es mejor `establece o un color_range, auto, o False` para señelar que solo se pone uno

2024-03-21 17:22 UTC, ayjayt commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# color_range=(lower_range, upper_range) funciones como un slice, y fijará los colores mínimo y máximo de esos rangos establecidos
rango_bajo? rango_alto?

si podemos usar español....

2024-03-21 17:22 UTC, ayjayt commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# dónde other_figure es un gráfico normal de un track
mejor `otra_figura`

2024-03-21 17:22 UTC, ayjayt commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +my_graph.render(xp=some_other_cross_plot_renderer)
`(xp=otro_renderizador_de_crossplot)` o algo

2024-03-21 17:24 UTC, neyberson commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# establece un color_range, auto, o False.
Tienes un buen español eh

2024-03-21 17:25 UTC, neyberson commented on docs/es/usarios/CROSSPLOTS-spanish.md
> +# color_range=(lower_range, upper_range) funciones como un slice, y fijará los colores mínimo y máximo de esos rangos establecidos
sí crees que debo cambiarlo entonces pongo todo lo que pueda en español

2024-03-22 19:03 UTC, ayjayt approved these changes

2024-03-22 19:03 UTC, merged