Utils
geopozo/pozo-py pull request #36
Opened 2024-05-23 21:45 UTC by neyberson

2024-05-24 15:45 UTC, ayjayt requested changes
Porfa

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/__init__.py
> +)
para las herramientas internas es mejor que usemos toda la ruta 'pozo.utils.array.cosa'

en vida, podemos hacerlo mas corta, pzutils.array.cosa

diferente si el usuario va a usarlo

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +import polars as pl
todavia no

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +    sample = depth[1] - depth[0]
no vamos a mantener un array, por que todavia tienes un array?

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +    sample = depth[1] - depth[0]
toda esta funcion es demasiada compleja para el resultado sencillo

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(depth, np.ndarray):
mejor que verifiquemos que tiene un `hasattr(depth, "tobytes")`?

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +        return hashlib.md5(str((depth_array.tobytes())).encode()).hexdigest()
odio la solucion pero puede ser que es la unica solucion

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +def is_array(value):
excluye porfavor pozo.Todo (Drawable, etc)

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +def is_scalar_number(value):
todavía no quiero usar esto, lo he dicho en otro comentario

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +def is_scalar_number(value):
(no quiero comprobar tipo, yo quiero usar algo mas flexible. puse un enlance en el otro comentario, no se cual es la mejor solution. talvez una prueba sencilla, si pede agregar)

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +                    "You mustn't use float('inf'), -float('inf'), float('nan')"
costosa la operacion

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +                    "You mustn't use float('inf'), -float('inf'), float('nan')"
tambien hay `np. isfinite() `

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.min(skipna=True)
`hasattr(data, "min")`

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.min()
que pasa con `na` aca?

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +        if not isinstance(data, np.ndarray):
mira @neyberson todavia no usas ducktyping, pero hemos hablado de esto unas veces. no vas a comprobar el tipo exacto, vas a comprobar la capabilidad del objeto

2024-05-24 15:45 UTC, ayjayt commented on pozo/utils/array.py
> +
yo termino acá porque los patrones son los mismos, voy a reempezar despues de las corecciones

2024-05-24 16:30 UTC, neyberson commented on pozo/utils/array.py
> +import polars as pl
El problema es que el modulo array.py ya tiene funciones que usan pandas y polars, si borro eso esas funciones dejan de servir y los test mandan error

2024-05-24 17:27 UTC, neyberson commented on pozo/utils/array.py
> +    sample = depth[1] - depth[0]
Ya lo arreglé, pero he estado revisando y creo que tengo un error con step y size, debo revisar mejor

2024-05-27 17:43 UTC, neyberson commented on pozo/utils/array.py
> +        return data.min(skipna=True)
aún estoy viendo con qué atributo hacer hasattr para cada tipo de objeto

2024-05-27 18:52 UTC, ayjayt requested changes
todavía no va con el concepto pythonista de "ducktyping"

evita usar `isinstance` porfavor

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/__init__.py
> +# Taken by the principal __ini__.py
podemos quitar este omentario, y poner un comentario descriptivo de la función

2024-05-27 18:52 UTC, ayjayt commented on pozo/__init__.py
> +# will migrate to utils folder
meh este comentario

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +        if isinstance(depth, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping
no quiero revisar directamente por tipo, no necesitamos usar `pd`

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +        if isinstance(depth, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +        warnings.warn("You must import polars to use this function")
nop, no tienes que import polar si nos dan un objeto de polar

si la funcion es del tipo
`polar.nan_max()`, se necesita polar

si la función es del tipo
´miCosa.nan_max()` solo tenemos que revisar que tenga el atributo `nan_max` y es suficiente usarlo así

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +        if not isinstance(data, np.ndarray):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +        if not isinstance(data, np.ndarray):
(este puede ser excepción)

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, (pl.Series, pl.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.Series):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.Series):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
quitando dependencias: ducktyping

2024-05-27 18:52 UTC, ayjayt commented on tests/utils/test_array.py
> +import polars as pl
en los test, esta bien

2024-05-27 20:48 UTC, ayjayt commented on pozo/utils/array.py
> +        try:
tienes demasiado en el try- solo el import, no la función, y debes comprobar si ya lo tenemos (mira las opciones por stackexchange)

2024-05-28 13:59 UTC, neyberson commented on pozo/utils/__init__.py
> +)
Done

2024-05-28 14:00 UTC, neyberson commented on pozo/utils/array.py
> +                    "You mustn't use float('inf'), -float('inf'), float('nan')"
Done

2024-05-28 14:01 UTC, neyberson commented on pozo/utils/array.py
> +        return data.min(skipna=True)
Done

2024-05-28 14:01 UTC, neyberson commented on pozo/utils/array.py
> +        return data.min()
Done

2024-05-28 14:01 UTC, neyberson commented on pozo/utils/array.py
> +        if not isinstance(data, np.ndarray):
Done

2024-05-28 14:25 UTC, neyberson commented on pozo/utils/array.py
> +def is_array(value):
Done

2024-05-28 16:35 UTC, neyberson commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
Done

2024-05-28 16:35 UTC, neyberson commented on pozo/utils/array.py
> +    elif isinstance(data, pl.Series):
Done

2024-05-28 16:35 UTC, neyberson commented on pozo/utils/array.py
> +    if isinstance(data, (pd.Series, pd.DataFrame)):
Done

2024-05-28 16:35 UTC, neyberson commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
Done

2024-05-28 17:53 UTC, ayjayt requested changes

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +            globals()["np"] = np
no

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +    if "np" not in globals():
revisa como hacerlo mejor, como te avisé, o explicame porque es solo `globals()`

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +def check_numpy():
y lo mismo para polar, y panda, y xarray

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +
esto no es correcto

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +            raise ValueError("Pozo does not support this object for this function")
_() y mejor el error

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +        raise ValueError("You mustn't use float('inf'), -float('inf'), float('nan')")
_()

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +                "Please install numpy. It must be installed like: pip install numpy"
_()

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +            raise ValueError("Pozo does not support this object for this function")
_()

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +        warnings.warn("You must import polars to use this function")
solo si hay problema hacemos un `.warn`

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +        return ~data.isin([np.inf, -np.inf])
mmmmm lo dudo....

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
no es...

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.isnull().any().any()
hmmmmmmm este se ve raro, definitivemente debes explicar

2024-05-28 17:53 UTC, ayjayt commented on pozo/utils/array.py
> +            raise ValueError("Pozo does not support this object for this function")
realmente no entiendo que es la idea acá, cual error queremos atrapar?

2024-05-28 19:19 UTC, neyberson commented on pozo/utils/array.py
> +            raise ValueError("Pozo does not support this object for this function")
Si pasan algún objeto que no sea de pandas, polars, una lista, una tupla o un array de numpy

2024-05-28 19:26 UTC, ayjayt commented on pozo/utils/array.py
> +            raise ValueError("Pozo does not support this object for this function")
que tiene que ver con `np.isfinite`? Este error se va a levantar durante la llama de `np.isfinite`.

2024-05-29 14:18 UTC, neyberson commented on pozo/utils/array.py
> +        return ~data.isin([np.inf, -np.inf])
Cómo así?

2024-05-29 20:38 UTC, neyberson commented on pozo/utils/array.py
> +def is_scalar_number(value):
Borré la función

2024-05-29 20:40 UTC, neyberson commented on pozo/utils/array.py
> +    elif isinstance(data, pl.DataFrame):
Ya lo arreglé, ya el archivo no tiene la importación de pandas y polars

2024-06-06 15:59 UTC, ayjayt commented on pozo/utils/array.py
> +import polars as pl
no, no vamos a incluir pandas ni polars

2024-06-06 15:59 UTC, ayjayt commented on pozo/utils/array.py
> +    steps = []
no vamos a guardar tablas, este no es necesario

2024-06-06 16:05 UTC, ayjayt commented on pozo/utils/array.py
> +    return math.isclose(a=a, b=b, rel_tol=rel_tol, abs_tol=abs_tol)
pero quiero el valor relativo a la variable a, y no se sí es...

2024-06-06 16:06 UTC, ayjayt commented on pozo/utils/array.py
> +    if hasattr(depth, "tobytes"):
esta funciona para toda table?

2024-06-06 16:07 UTC, ayjayt commented on pozo/utils/array.py
> +        raise ValueError(_("You mustn't use pozo objects for this function"))
.... no es neesario leventar un error? se han preguntado si es una table y la respuesta correcta es "False"

2024-06-06 16:17 UTC, ayjayt commented on pozo/utils/array.py
> +@doc(_d("""min use 1 parameter to find the max value"""))
min o max

2024-06-06 16:17 UTC, ayjayt commented on pozo/utils/array.py
> +        return np.fabs(data)
que esta pasando acá? xarray no tiene una funcion de abs?

2024-06-06 16:18 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.abs()
esta bien con pandas, polars, series, etc?

2024-06-06 16:19 UTC, ayjayt commented on pozo/utils/array.py
> +    elif hasattr(data, "coords"):  # xarray
por que no busca "values"

2024-06-06 16:19 UTC, ayjayt commented on pozo/utils/array.py
> +        return np.fabs(data)
y por que acá no se usa "values?"

2024-06-06 16:19 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.isnull().any()
esto me parece raro

2024-06-06 16:28 UTC, ayjayt commented on pozo/utils/array.py
> +        return np.count_nonzero(data.to_numpy())
mmmm haciendo conversiones.... no lo amo

2024-06-06 16:29 UTC, ayjayt commented on pozo/utils/array.py
> +def round(data, decimals=0, **kargs):
esto todavia me parece raro

2024-06-06 16:32 UTC, ayjayt commented on pozo/utils/array.py
> +        return np.count_nonzero(data.to_numpy())
es que, si tiene to_numpy usamos el mismo algoritmo por que no pones eso en vez de las ramas distintas?

2024-06-06 16:32 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.quantile(q)
por que no buscas quantile?

2024-06-06 16:33 UTC, ayjayt commented on pozo/utils/array.py
> +        return data.quantile(q)
y puedes incluir la función bajo

2024-06-06 16:33 UTC, ayjayt commented on pozo/utils/array.py
> +def append(data, arg):
este realmente quiero arreglar....

2024-06-06 16:33 UTC, ayjayt commented on pyproject.toml
> +  "polars >= 0.20.26"
y xarray?

2024-06-06 16:34 UTC, ayjayt commented on tests/utils/test_array.py
> +list_data_irregular = [0, 20, 40, 50, 70, 90, 300, 301, 330, 400]
otra vez, una funcion prfa

2024-06-06 16:38 UTC, ayjayt commented
tambien, la otra cosa es que me equiviqué pidiendo `@doc(_d()))` - se puede usar `#` normal porque son internas. perdón. Tabién `@doc(_d()))` se usa una estructura fija, debes revisar los ejemplos para ver como se ponen las variables y salidas

2024-06-06 21:30 UTC, neyberson commented on pozo/utils/array.py
> +    if hasattr(depth, "tobytes"):
listas, tuplas, numpy arrays y series (pandas y polars)

2024-06-06 21:44 UTC, neyberson commented on pozo/utils/array.py
> +        return np.fabs(data)
La función que tiene para abs afecta a todos los datos, pero si solo se escoge la coordenada(objeto de xarray) de la profundidad y se hace .values, extrae un array de numpy y ese se puede usar como si fuera cualquier otro array de numpy

2024-06-06 21:44 UTC, neyberson commented on pozo/utils/array.py
> +        return data.abs()
sí, lo probé

2024-06-06 21:59 UTC, neyberson commented on pozo/utils/array.py
> +    elif hasattr(data, "coords"):  # xarray
porque "coords" es específico de un objeto de xarray, "values" es válido para xarray y también para pandas

2024-06-06 22:01 UTC, neyberson commented on pozo/utils/array.py
> +        return data.isnull().any()
Es porque el método en pandas devuelve toda la serie pero con valores booleanos, entonces al hacer .any() le pido que revise si de todos alguno es True y ya con eso se ahorra memoria

2024-06-06 22:02 UTC, neyberson commented on pozo/utils/array.py
> +def append(data, arg):
Pude arreglar el problema que tenía, solo era cambiar el hasattr, era algo tonto en realidad, pero demoré en darme cuenta

2024-06-07 14:10 UTC, neyberson commented on pozo/utils/array.py
> +    if hasattr(depth, "tobytes"):
hash_array, funciona para: listas, tuplas, numpy arrays y series (Polars y Pandas)

2024-06-07 14:17 UTC, neyberson commented on pozo/utils/array.py
> +        return np.count_nonzero(data.to_numpy())
Done

2024-06-07 14:48 UTC, neyberson commented on pozo/utils/array.py
> +        return data.quantile(q)
Done

2024-06-07 15:28 UTC, neyberson commented on pyproject.toml
> +  "polars >= 0.20.26"
Done

2024-06-07 15:29 UTC, neyberson commented on pozo/utils/array.py
> +def append(data, arg):
Exactamente qué quieres arreglar?

2024-06-07 15:30 UTC, neyberson commented on pozo/utils/array.py
> +    return math.isclose(a=a, b=b, rel_tol=rel_tol, abs_tol=abs_tol)
Cómo así?

2024-06-20 17:20 UTC, closed without merging